# Generated by Django 2.0.5 on 2018-05-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('num', models.IntegerField(default='None', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(auto_now=True)),
                ('pc', models.ManyToManyField(to='registro.Pc')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(default='None', max_length=60)),
                ('ced', models.CharField(default='-1', max_length=60, primary_key=True, serialize=False, unique=True)),
                ('cod', models.CharField(default='None', max_length=60, unique=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.Program')),
            ],
        ),
        migrations.AddField(
            model_name='registry',
            name='student',
            field=models.ManyToManyField(to='registro.Student'),
        ),
    ]
