# Generated by Django 2.0.5 on 2018-05-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='pc_disp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='registry',
            name='pc',
        ),
        migrations.AddField(
            model_name='registry',
            name='pc',
            field=models.OneToOneField(default=None, on_delete=False, to='registro.Pc'),
        ),
        migrations.RemoveField(
            model_name='registry',
            name='student',
        ),
        migrations.AddField(
            model_name='registry',
            name='student',
            field=models.OneToOneField(default=None, on_delete=False, to='registro.Student'),
        ),
    ]
