# Generated by Django 6.0.2 on 2026-03-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.pc'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.student'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
