# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='departure_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
