# Generated by Django 2.0.5 on 2018-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180516_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cod',
            field=models.CharField(default='None', max_length=3, unique=True),
        ),
    ]
