# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180601_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
