# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20180606_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='departure_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
