# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20180606_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='pc',
        ),
        migrations.AddField(
            model_name='registry',
            name='pc',
            field=models.ManyToManyField(to='registro.Pc'),
        ),
        migrations.RemoveField(
            model_name='registry',
            name='student',
        ),
        migrations.AddField(
            model_name='registry',
            name='student',
            field=models.ManyToManyField(to='registro.Student'),
        ),
    ]
