# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20180606_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registry',
            new_name='Loan',
        ),
    ]
