# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20180606_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='departure_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='pc',
        ),
        migrations.AddField(
            model_name='loan',
            name='pc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='registro.Pc'),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='student',
        ),
        migrations.AddField(
            model_name='loan',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='registro.Student'),
        ),
    ]
