# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20180606_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='departure_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
